### ISSUE TITLE
Game Lag (not playable)

### ISSUE THREAD

**Issue by tobytes** [RainbowSaber/WoT-Dev-4#40]
Hi,
I like the concept but the modpack is sadly not playable for me.
The world is lagging and harvested items are jumping back in place.

> [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 22647ms behind, skipping 452 tick(s)

I uploaded my MultiMC-Log, maybe it helps:
[Logfile](https://gist.githubusercontent.com/tobytes/499ebd6001d3842ea8d3c2e02c8926eb/raw/8a82ebb963a1ee0caa2385fb3972edd31f8a8ef6/multimc-wheeloftime.txt)

**Comment by RainbowSaber** [comment]
Heya, unfortunately the worldgen is very slow. Once terrain has been generated the performance is pretty great actually

**Comment by tobytes** [comment]
Thank, you for the response.
 I see your point and after waiting a while I am able to play until I try to walk around and explore. Maybe too much for my pc.
